### ISSUE TITLE
Weird strings that give errors when parsing with lenient_parse.to_float

### ISSUE THREAD

**Issue by mooreryan** [JosephTLyons/lenient_parse#86]
Just a couple of the potentially interesting strings that I found with the property tests.

- this one is interesting:
    - original: `"+2_2_6_275_1.\r\n\u{000B}\n\n "`, shrunk: `"9.\t"`, error: `UnknownCharacter(13, "\r\n")`
    - Python gives: `2262751.0` for original and `9.0` for shrunk

These ones probably should be treated as expected for now:

- numbers that go out of bounds (expected to crash)
    - original: `"\r \r\r\t-0_09.0_0_1E+7_7_0_4_6\t\u{000B}"`, shrunk: `".9E999"`
- non-finite (expected crash really)
    - original: `"\u{000B}\f\r\n\t\r\r+iNFiNITy\n\u{000B}\u{000B}\f\r\n\t\r\r"`, shrunk: `"iNFiNITy"`
    - (I imagine `nan` will give the similar)

--- 

I will hold off on putting more here for now.  The subsequent ones that are unexpected as I find them, I will put into example test cases to anchor the tests.

**Comment by JosephTLyons** [comment]
Much appreciated @mooreryan! I'll dig into some of this over break! :)

**Comment by JosephTLyons** [comment]
For the first bug you wrote, you were able to get python to parse this?

```
+2_2_6_275_1.\r\n\u{000B}\n\n 
```

Python doesn't like whitespace next to the `.` character:

```
>>> float("1.0")
1.0
>>> float("1. 0")
Traceback (most recent call last):
  File "<python-input-6>", line 1, in <module>
    float("1. 0")
    ~~~~~^^^^^^^^
ValueError: could not convert string to float: '1. 0'
>>> float("1.\n0")
Traceback (most recent call last):
  File "<python-input-7>", line 1, in <module>
    float("1.\n0")
    ~~~~~^^^^^^^^^
ValueError: could not convert string to float: '1.\n0'
>>> float("1.0\n")
1.0
```

And `\r\n` is a whitespace character. I could be missing something here.

**Comment by JosephTLyons** [comment]
I see now, this is all trailing whitespace, so something weird is def going on.

**Comment by mooreryan** [comment]
Yeah, as you say it's all trailing.  E.g.,

```python
>>> float("+2_2_6_275_1.\r\n\u000B\n\n ")
2262751.0
```

(That's python 3.13.0 at least.)

**Comment by JosephTLyons** [comment]
Yep, gotcha. The shrinking is super cool. Yep, this case covers it:

```gleam
FloatTestData(
  input: "0. ",
  expected_program_output: Ok(0.0),
  expected_python_output: Ok("0.0"),
),
```
